version: "3.8"

services:
  rathole-client:
    image: rapiz1/rathole:v0.4.7
    container_name: rathole-client
    restart: unless-stopped
    network_mode: host
    command: ["--client", "/app/client.toml"]
    volumes:
      - ./client.toml:/app/client.toml
